function mainLayout(status,file)
   hs = build(200,430);
   hs.fig.Visible = 'on';
   function hs = build(height,width)
       hs.fig = figure('Visible','off',...
                  'Resize','off',...
                  'Tag','fig',...
                  'Position',[200 200 width height]);
       hs.label=uicontrol(hs.fig,'Style','text',...
                'FontSize',12,...
                'String','Nano Roughness',...
                'FontWeight','bold',...
                'Position',[0 height-50 width 50]);
       hs.btn = uicontrol(hs.fig,...
                  'String','Choose File...',...
                  'Tag','button',...
                  'Callback',@buttonCallback,...
                  'Position',[10 height-80 200 30]);
       hs.btn.Visible='on';
       
       hs.btn3 = uicontrol(hs.fig,...
                  'String','Generate Random Data Set...',...
                  'Tag','button3',...
                  'Callback',@buttonCallback,...
                  'Position',[10 height-120 200 30]);
       hs.btn4 = uicontrol(hs.fig,...
                  'String','Input Data Set...',...
                  'Tag','button4',...
                  'Callback',@buttonCallback,...
                  'Position',[220 height-80 200 30]);
       
       
       if status==1
           hs.btn3.Visible='on';
           hs.btn4.Visible='on';
       else
           hs.btn3.Visible='off';
           hs.btn4.Visible='off';
       end
       hs.btn2 = uicontrol(hs.fig,...
                  'String','Quit',...
                  'Tag','button2',...
                  'Callback',@buttonCallback,...
                  'Position',[width/2-100 10 200 30]);
       hs.btn5 = uicontrol(hs.fig,...
                  'String','About...',...
                  'Tag','button5',...
                  'Callback',@buttonCallback,...
                  'Position',[width/2-100 40 200 30]);
   end
   

   function buttonCallback(hObject,event)
        if(strcmp(hObject.Tag,'button'))
            close all
            fileLayout();
        elseif(strcmp(hObject.Tag,'button2'))
            close all
        elseif(strcmp(hObject.Tag,'button3'))
            close all
            y = randi(length(file(:,1)));
            x = randi(length(file(1,:)));
            len = randi(138);
            dataLayout(file,[x y],len,randi(4)-1);
        elseif(strcmp(hObject.Tag,'button4'))
            close all
            inputLayout(file);
        elseif(strcmp(hObject.Tag,'button5'))
            close all
            aboutLayout(status,file);
        end
   end
end