function aboutLayout(status,file)
   hs = build(500,430);
   hs.fig.Visible = 'on';
   function hs = build(height,width)
       hs.fig = figure('Visible','off',...
                  'Resize','off',...
                  'Tag','fig',...
                  'Position',[200 200 width height]);
       hs.label=uicontrol(hs.fig,'Style','text',...
                'FontSize',12,...
                'String','About',...
                'FontWeight','bold',...
                'Position',[0 height-50 width 50]);
      
            hs.label=uicontrol(hs.fig,'Style','text',...
                'FontSize',10,...
                'String',char("        Developed by Team D:                     Andrés Quevedo                          Diego Maguey                             Javier Prieto                 Luis Hernández"),...
                'FontWeight','bold',...
                'Position',[width/2-100 20 200 400]);
       
       hs.btn2 = uicontrol(hs.fig,...
                  'String','Back',...
                  'Tag','button2',...
                  'Callback',@buttonCallback,...
                  'Position',[width/2-100 10 200 30]);
   end
   

   function buttonCallback(hObject,event)
       close all
       mainLayout(status,file);
        
   end
end